dcConsData = [
	{"name":"꾸동냥이.png", 					"keywords":["구독냥이", "꾸동냥이"], 									"tags":["역가"]},
	{"name":"역가평가.png", 					"keywords":["역가평가", "이그레인평가"], 							"tags":["역가"]},
	{"name":"역자평가.png", 					"keywords":["역자평가"], 															"tags":["주토피아", "피닉"]},
	{"name":"식자평가.png",						"keywords":["식자평가"], 															"tags":["주토피아", "닉"]},
	{"name":"주톱아너무.png",				 	"keywords":["주톱아너무무섭다", "주톱아너무"], 				"tags":["컬러케장", "주토피아", "닉"]},
	{"name":"주톱오홍홍.png", 				"keywords":["주톱오홍홍"], 														"tags":["케장콘", "주토피아", "주디"]},
	{"name":"주톱빳다죠1.png", 				"keywords":["주톱당근빳다죠1", "주톱당근빳다죠", "주톱빳다죠1", "주톱빳다죠"],
																																													"tags":["케장콘", "주토피아", "주디"]},
	{"name":"주톱빳다죠2.png", 				"keywords":["주톱당근빳다죠2", "주톱빳다죠2"], 				"tags":["케장콘", "주토피아", "닉"]},
	{"name":"주톱호랑이1.gif", 				"keywords":["호랑이1", "호랑이"], 										"tags":["주토피아", "움짤"]},
	{"name":"주톱호랑이2.gif", 				"keywords":["호랑이2"],																"tags":["주토피아", "움짤"]},
	{"name":"주톱호랑이3.gif", 				"keywords":["호랑이3"],																"tags":["주토피아", "움짤"]},
	{"name":"주톱호랑이4.gif", 				"keywords":["호랑이4"],																"tags":["주토피아", "움짤"]},

	{"name":"싸닉.png",								"keywords":["싸닉"],																	"tags":["케장콘", "소닉"]},
	{"name":"싸닉따일즈.png",					"keywords":["따일즈"],																"tags":["케장콘", "소닉", "테일즈"]},
	{"name":"싸닉나클즈.png",					"keywords":["나클즈"],																"tags":["케장콘", "소닉", "너클즈"]},
	{"name":"소닉ㄳ.png",							"keywords":["소닉ㄳ"],																"tags":["케장콘", "소닉"]},
	{"name":"소닉말잇못.png",					"keywords":["소닉말을잇지못하는", "소닉말잇못"],			"tags":["케장콘", "소닉", "테일즈"]},
	{"name":"소닉시불장.png",					"keywords":["소닉시불장"],														"tags":["케장콘", "소닉", "너클즈"]},
	{"name":"소닉쒸발년아.png",				"keywords":["소닉쒸발년아"],													"tags":["케장콘", "소닉", "에이미"]},
	{"name":"소닉왜그런대.png",				"keywords":["소닉왜그런대"],													"tags":["케장콘", "소닉", "에이미"]},
	{"name":"소닉한심.png",						"keywords":["소닉한심"],															"tags":["케장콘", "소닉"]},

	
	{"name":"손님빨갱이.gif",					"keywords":["빨갱이", "화남"],												"tags":["롤코타", "손님", "움짤"]},
	{"name":"손님멀미1.gif",					"keywords":["멀미", "멀미1"], 												"tags":["롤코타", "손님"]},
	{"name":"손님멀미2.gif",					"keywords":["멀미2"],																	"tags":["롤코타", "손님", "움짤"]},
	{"name":"손님멀미3.gif", 					"keywords":["멀미3"],																	"tags":["롤코타", "손님", "움짤"]},
	{"name":"손님피곤.gif", 					"keywords":["피곤"],																	"tags":["롤코타", "손님"]},
	{"name":"손님행복1.gif", 					"keywords":["행복", "행복1"],													"tags":["롤코타", "손님"]},
	{"name":"손님행복2.gif", 					"keywords":["행복2"],																	"tags":["롤코타", "손님"]},
	{"name":"손님무표정.gif", 				"keywords":["무표정"], 																"tags":["롤코타", "손님"]},
	{"name":"손님불행1.gif", 					"keywords":["불행", "불행1"],													"tags":["롤코타", "손님"]},
	{"name":"손님불행2.gif", 					"keywords":["불행2"], 																"tags":["롤코타", "손님"]},

	{"name":"롤코기가.png",						"keywords":["기가"],																	"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코나선.png",						"keywords":["나선"],																	"tags":["롤코타", "롤러코스터"]},	
	{"name":"롤코레이다운.png",				"keywords":["레이다운"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코루핑.png",						"keywords":["루핑"],																	"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코리버서.png",					"keywords":["리버서"],																"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코리버스프리폴.png",		"keywords":["리버스프리폴", "역방향자유낙하"],				"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코마인.png",						"keywords":["마인"],																	"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코림발진.png",					"keywords":["림발진"],																"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코멀티디멘션.png",			"keywords":["멀티디멘션"],														"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코미니.png",						"keywords":["미니"],																	"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코미니서스펜디드.png",	"keywords":["미니서스펜디드"],												"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코버지니아.png",				"keywords":["버지니아"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코봅슬레이.png",				"keywords":["봅슬레이"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코사이드프릭션.png",		"keywords":["사이드프릭션"],													"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코서스펜디드.png",			"keywords":["서스펜디드"],														"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코수직낙하.png",				"keywords":["수직낙하"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코스탠드업.png",				"keywords":["스탠드업"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코스티플체이스.png",		"keywords":["스티플체이스"],													"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코스파이럴.png",				"keywords":["스파이럴"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코에어파워드버티컬.png",
																		"keywords":["에어파워드버티컬"],											"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코와일드마우스.png",		"keywords":["와일드마우스"],													"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코우든.png",						"keywords":["우든"],																	"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코우든와일드광산.png",	"keywords":["우든와일드광산"],												"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코우든와일드마우스.png",
																		"keywords":["우든와일드마우스", "우든와일드"],				"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코우든트위스터.png",		"keywords":["우든트위스터"],													"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코워터코스터.png",			"keywords":["워터코스터"],														"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코인버티드.png",				"keywords":["인버티드"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코주니어.png",					"keywords":["주니어"],																"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코컴팩트인버티드.png",	"keywords":["컴팩트인버티드"],												"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코탄광.png",						"keywords":["탄광"],																	"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코트위스터.png",				"keywords":["트위스터"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코플라잉.png",					"keywords":["플라잉"],																"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코플라잉턴.png",				"keywords":["플라잉턴"],															"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코플로어리스.png",			"keywords":["플로어리스"],														"tags":["롤코타", "롤러코스터"]},
	{"name":"롤코하트라인.gif",				"keywords":["하트라인"],															"tags":["롤코타", "롤러코스터"]},
	
	
	{"name":"기구2층전망탑.png",			"keywords":["2층전망탑"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구2층회전목마.png",		"keywords":["2층회전목마"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구360도바이킹.png",		"keywords":["360도바이킹"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구고카트.png",					"keywords":["고카트"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구골프.png",						"keywords":["골프", "미니골프", "민희골프"],					"tags":["롤코타", "놀이기구"]},		
	{"name":"기구관람차.png",					"keywords":["관람차"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구귀신의집.png",				"keywords":["귀신의집"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구나선미끄럼틀.png",		"keywords":["나선미끄럼틀", "미끄럼틀"],							"tags":["롤코타", "놀이기구"]},
	{"name":"기구떼껄룩카라이드.png",	"keywords":["떼껄룩카라이드"],												"tags":["롤코타", "놀이기구"]},
	{"name":"기구런치드프리폴.png",		"keywords":["런치드프리폴"],													"tags":["롤코타", "놀이기구"]},
	{"name":"기구리버래프트.png",			"keywords":["리버래프트"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구리버래피드.png",			"keywords":["리버래피드"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구메이즈.png",					"keywords":["메이즈"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구모노레일.png",				"keywords":["모노레일"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구모형기차.png",				"keywords":["모형기차"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구모션시뮬레이터.png",	"keywords":["모션시뮬레이터"],												"tags":["롤코타", "놀이기구"]},
	{"name":"기구미니헬리콥터.png",		"keywords":["미니헬리콥터", "미니헬리곱터"],													"tags":["롤코타", "놀이기구"]},
	{"name":"기구바이킹.png",					"keywords":["바이킹"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구백조보트.png",				"keywords":["백조보트"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구범퍼카.png",					"keywords":["범퍼카"],																"tags":["롤코타", "놀이기구"]},	
	{"name":"기구보트.png",						"keywords":["보트"],																	"tags":["롤코타", "놀이기구"]},
	{"name":"기구비행접시.png",				"keywords":["비행접시"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구삐뚤어진집.png",			"keywords":["삐뚤어진집", "비뚤어진집"],							"tags":["롤코타", "놀이기구"]},
	{"name":"기구서스펜디드모노레일.png",
																		"keywords":["서스펜디드모노레일"],										"tags":["롤코타", "놀이기구"]},
	{"name":"기구서커스.png",					"keywords":["서커스"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구스페이스링.png",			"keywords":["스페이스링"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구스플래시보트.png",		"keywords":["스플래시보트", "보트라이드"],						"tags":["롤코타", "놀이기구"]},
	{"name":"기구양탄자.png",					"keywords":["양탄자"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구엔터프라이즈.png",		"keywords":["엔터프라이즈"],													"tags":["롤코타", "놀이기구"]},
	{"name":"기구엘리베이터.png",			"keywords":["엘리베이터", "리프트"],									"tags":["롤코타", "놀이기구"]},
	{"name":"기구영화관.png",					"keywords":["영화관"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구워터슬라이드.png",		"keywords":["워터슬라이드"],													"tags":["롤코타", "놀이기구"]},
	{"name":"기구유령기차.png",				"keywords":["유령기차"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구자이로드롭.png",			"keywords":["자이로드롭"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구자전거.png",					"keywords":["자전거"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구전망탑.png",					"keywords":["전망탑"],																"tags":["롤코타", "놀이기구"]},
	{"name":"기구체어리프트.png",			"keywords":["체어리프트"],														"tags":["롤코타", "놀이기구"]},
	{"name":"기구카누.png",						"keywords":["카누"],																	"tags":["롤코타", "놀이기구"]},
	{"name":"기구카라이드.png",				"keywords":["카라이드"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구탑스핀.png",					"keywords":["탑스핀", "톱스핀"],											"tags":["롤코타", "놀이기구"]},
	{"name":"기구트램.png",						"keywords":["트램", "전차"],													"tags":["롤코타", "놀이기구"]},
	{"name":"기구트위스트.png",				"keywords":["트위스트"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구회전목마.png",				"keywords":["회전목마"],															"tags":["롤코타", "놀이기구"]},
	{"name":"기구후룸라이드.png",			"keywords":["후룸라이드"],														"tags":["롤코타", "놀이기구"]},

	{"name":"상점ATM.png",						"keywords":["ATM"],																		"tags":["롤코타", "상점"]},
	{"name":"상점감자칩.png",					"keywords":["감자칩가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점감자튀김.png",				"keywords":["감자튀김가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점고기국수.png",				"keywords":["고기국수가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점고기완자탕.png",			"keywords":["고기완자탕가게"],												"tags":["롤코타", "상점"]},
	{"name":"상점기념품.png",					"keywords":["기념품가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점도넛.png",						"keywords":["도넛가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점두유.png",						"keywords":["두유가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점레모네이드.png",			"keywords":["레모네이드가게"],												"tags":["롤코타", "상점"]},
	{"name":"상점만두국.png",					"keywords":["만두국가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점모자.png",						"keywords":["모자가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점병원.png",						"keywords":["병원"],																	"tags":["롤코타", "상점"]},
	{"name":"상점사과사탕.png",				"keywords":["사과사탕가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점샌드위치.png",				"keywords":["샌드위치가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점선글라스.png",				"keywords":["선글라스가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점소세지.png",					"keywords":["소세지가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점솜사탕.png",					"keywords":["솜사탕가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점수정과.png",					"keywords":["수정과가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점스타프루트.png",			"keywords":["스타프루트가게"],												"tags":["롤코타", "상점"]},
	{"name":"상점아이스크림.png",			"keywords":["아이스크림가게"],												"tags":["롤코타", "상점"]},
	{"name":"상점아이스크림콘.png",		"keywords":["아이스크림콘가게"],											"tags":["롤코타", "상점"]},
	{"name":"상점아이스티.png",				"keywords":["아이스티가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점안내소.png",					"keywords":["안내소"],																"tags":["롤코타", "상점"]},
	{"name":"상점음료수.png",					"keywords":["음료수가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점촉수.png",						"keywords":["촉수가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점치킨.png",						"keywords":["치킨가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점치킨너겟.png",				"keywords":["치킨너겟가게"],													"tags":["롤코타", "상점"]},
	{"name":"상점커피.png",						"keywords":["커피가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점케이크쿠키.png",			"keywords":["케이크가게", "쿠키가게", "쿠기가게"],		"tags":["롤코타", "상점"]},
	{"name":"상점튀김쌀국수.png",			"keywords":["튀김쌀국수가게"],												"tags":["롤코타", "상점"]},
	{"name":"상점티셔츠.png",					"keywords":["티셔츠가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점팝콘.png",						"keywords":["팝콘가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점풍선.png",						"keywords":["풍선가게"], 															"tags":["롤코타", "상점"]},
	{"name":"상점프레첼.png",					"keywords":["프레첼가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점피자.png",						"keywords":["피자가게"],															"tags":["롤코타", "상점"]},
	{"name":"상점핫도그.png",					"keywords":["핫도그가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점핫초코.png",					"keywords":["핫초코가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점햄버거.png",					"keywords":["햄버거가게"],														"tags":["롤코타", "상점"]},
	{"name":"상점화장실.png",					"keywords":["화장실"],																"tags":["롤코타", "상점"]},
	
	{"name":"롤코유리궁전.png",				"keywords":["유리궁전"],															"tags":["케장콘", "롤코타"]},
	{"name":"니공원재정.gif",					"keywords":["니공원재정"], 														"tags":["케장콘", "롤코타", "움짤"]},
	{"name":"니공원등급.png",					"keywords":["니공원등급"], 														"tags":["케장콘", "롤코타"]},
	{"name":"니공원손님.gif",					"keywords":["니공원손님"], 														"tags":["케장콘", "롤코타", "움짤"]},
	
	
	{"name":"볼트넷여친.png",					"keywords":["볼트넷여친"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트넷친구.png",					"keywords":["볼트넷친구"], 														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트동정.png",						"keywords":["볼트동정"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트가정사.png",					"keywords":["볼트가정사"], 														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트등골.png",						"keywords":["볼트등골"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트병신.png",						"keywords":["볼트병신"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트나무.png",						"keywords":["볼트나무"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트대머리.png",					"keywords":["볼트대머리", "볼트머머리", "볼트대대리", "볼트머대리"],
																																													"tags":["폴아웃", "베데스다"]},
	{"name":"볼트침대.png",						"keywords":["볼트침대"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트활활.png",						"keywords":["볼트활활"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트댕댕.png",						"keywords":["볼트댕댕"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트기계.png",						"keywords":["볼트기계"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트결혼.png",						"keywords":["볼트결혼"], 															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트비밀친구.png",				"keywords":["볼트비밀친구"], 													"tags":["폴아웃", "베데스다"]},
	{"name":"볼트군인.png",						"keywords":["볼트군인"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트닌자.png",						"keywords":["볼트닌자"],															"tags":["폴아웃", "베데스다", "일뽕"]},
	{"name":"볼트인육.png",						"keywords":["볼트인육"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트핫산.png",						"keywords":["볼트핫산"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트주사.png",						"keywords":["볼트주사"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트빼액.png",						"keywords":["볼트빼액"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트꺼져.png",						"keywords":["볼트꺼져"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트닥쳐.png",						"keywords":["볼트닥쳐"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트안마.png",						"keywords":["볼트안마"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트망치.png",						"keywords":["볼트망치"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트빠따.png",						"keywords":["볼트빠따"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트수류탄.png",					"keywords":["볼트수류탄"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트전기톱.png",					"keywords":["볼트전기톱"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트장전.png",						"keywords":["볼트장전"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트저격.png",						"keywords":["볼트저격"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트라이플.png",					"keywords":["볼트라이플"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트화염병.png",					"keywords":["볼트화염병"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트주먹.png",						"keywords":["볼트주먹"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트컴온.png",						"keywords":["볼트컴온"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트투창.png",						"keywords":["볼트투창"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트아킴보.png",					"keywords":["볼트아킴보"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트고인.png",						"keywords":["볼트고인"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트부활.png",						"keywords":["볼트부활"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트띠용.png",						"keywords":["볼트띠용"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트신문.png",						"keywords":["볼트신문"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트눈물.png",						"keywords":["볼트눈물"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트투시.png",						"keywords":["볼트투시"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트토끼.png",						"keywords":["볼트토끼"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트포기.png",						"keywords":["볼트포기"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트자살.png",						"keywords":["볼트자살"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트게이.png",						"keywords":["볼트게이"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트딸딸.png",						"keywords":["볼트딸딸"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트음주.png",						"keywords":["볼트음주"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트수면.png",						"keywords":["볼트수면"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트우승.png",						"keywords":["볼트우승"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트루저.png",						"keywords":["볼트루저"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트구토.png",						"keywords":["볼트구토"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트예수.png",						"keywords":["볼트예수"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트심리.png",						"keywords":["볼트심리"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트연설.png",						"keywords":["볼트연설"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트공중.png",						"keywords":["볼트공중"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트엄격.png",						"keywords":["볼트엄격"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트진지.png",						"keywords":["볼트진지"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트근엄.png",						"keywords":["볼트근엄"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트펄럭.png",						"keywords":["볼트펄럭"],															"tags":["폴아웃", "베데스다", "국뽕"]},
	{"name":"볼트답답.png",						"keywords":["볼트답답"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트절망.png",						"keywords":["볼트절망"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트관전.png",						"keywords":["볼트관전"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트통수.png",						"keywords":["볼트통수"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트연주.png",						"keywords":["볼트연주"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트파오후.png",					"keywords":["볼트파오후"],														"tags":["폴아웃", "베데스다"]},
	{"name":"볼트딴딴.png",						"keywords":["볼트딴딴"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트처형.png",						"keywords":["볼트처형"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트명상.png",						"keywords":["볼트명상"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트마약.png",						"keywords":["볼트마약"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트떠남.png",						"keywords":["볼트떠남"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트나치.png",						"keywords":["볼트나치"],															"tags":["폴아웃", "베데스다", "나치즘"]},
	{"name":"볼트근육.png",						"keywords":["볼트근육"],															"tags":["폴아웃", "베데스다"]},
	{"name":"볼트자본.png",						"keywords":["볼트자본"],															"tags":["폴아웃", "베데스다"]},
		
	{"name":"케장그러네.gif",					"keywords":["케장그러네"],														"tags":["케장콘"]},
	{"name":"케장그럴수도.png",				"keywords":["그럴수도있고", "아닐수도있고"],					"tags":["케장콘"]},
	{"name":"케장그렇군요.png",				"keywords":["그렇군요"],															"tags":["케장콘"]},
	{"name":"케장나무야.png",					"keywords":["나무야미안해"],													"tags":["케장콘"]},
	{"name":"케장난닷테.png",					"keywords":["케장난닷테", "난닷테"],									"tags":["케장콘"]},
	{"name":"케장남탓.png",						"keywords":["남탓"],																	"tags":["케장콘"]},
	{"name":"케장넹기분굿.png",				"keywords":["넹기분굿"],															"tags":["케장콘"]},
	{"name":"케장노잼.png",						"keywords":["노잼예스삭제", "노잼"],									"tags":["케장콘"]},
	{"name":"케장니상상속.gif",				"keywords":["니상상속", "케장니상상속"],							"tags":["케장콘"]},
	{"name":"케장돈의노예.png",				"keywords":["돈의노예"],															"tags":["케장콘"]},
	{"name":"케장두뇌.png",						"keywords":["두뇌가동중", "두뇌풀가동"],							"tags":["케장콘"]},
	{"name":"케장따봉.png",						"keywords":["따봉"],																	"tags":["케장콘"]},
	{"name":"케장말잇못.png",					"keywords":["말을잇지못하는", "말잇못"],							"tags":["케장콘"]},
	{"name":"케장머쓱.png",						"keywords":["머쓱"],																	"tags":["케장콘"]},
	{"name":"케장머임.png",						"keywords":["머임?"],																	"tags":["케장콘"]},
	{"name":"케장몰랏내.png",					"keywords":["고건몰랏내", "고건몰랐네"],							"tags":["케장콘"]},
	{"name":"케장무말모.png",					"keywords":["무말모", "무슨말인지모르겠네요"],				"tags":["케장콘"]},
	{"name":"케장물음표1.png",				"keywords":["???"],																		"tags":["케장콘"]},
	{"name":"케장물음표2.png",				"keywords":["?????"],																	"tags":["케장콘"]},
	{"name":"케장박수1.png",					"keywords":["박수", "박수1"],													"tags":["케장콘"]},
	{"name":"케장박수2.png",					"keywords":["박수2"],																	"tags":["케장콘"]},
	{"name":"케장박수3.png",					"keywords":["박수3"],																	"tags":["케장콘"]},
	{"name":"케장배꼽처치.png",				"keywords":["배꼽처치"],															"tags":["케장콘"]},
	{"name":"케장밸런스.png",					"keywords":["밸런스꼬라지", "밸런스"],								"tags":["케장콘"]},
	{"name":"케장빗물.png",						"keywords":["빗물샌다", "천장"],											"tags":["케장콘"]},
	{"name":"케장빳다죠.png",					"keywords":["당근빳다죠"], 														"tags":["케장콘"]},
	{"name":"케장사고가.png",					"keywords":["사고가", "사고가이래서"],								"tags":["케장콘"]},
	{"name":"케장설명충.png",					"keywords":["설명충극혐", "케장안물", "케장안물1"],	"tags":["케장콘"]},
	{"name":"케장수요의노예.png",			"keywords":["수요의노예"],														"tags":["케장콘"]},
	{"name":"케장신고감.png",					"keywords":["신고감이다"],														"tags":["케장콘"]},
	{"name":"케장아너무.png",					"keywords":["아너무무섭다"],													"tags":["케장콘"]},
	{"name":"케장안사요.png",					"keywords":["안사요", "아안사요"],										"tags":["케장콘"]},
	{"name":"케장알고싶던.png",				"keywords":["케장알고싶던", "케장안물2"],							"tags":["케장콘"]},
	{"name":"케장알않데스.png",				"keywords":["알고싶지않은데스", "케장안물3"],					"tags":["케장콘"]},
	{"name":"케장알파카.png",					"keywords":["알파카", "대신귀여운"],									"tags":["케장콘"]},
	{"name":"케장양심.png",						"keywords":["양심지수"],															"tags":["케장콘"]},
	{"name":"케장에에엥.gif",					"keywords":["케장에에엥"],														"tags":["케장콘"]},
	{"name":"케장오홍홍.png",					"keywords":["오홍홍"],																"tags":["케장콘"]},
	{"name":"케장억떡계.png",					"keywords":["케장억떡계", "케장어떻게"],							"tags":["케장콘"]},
	{"name":"케장어쩌라고.png",				"keywords":["어쩌라고", "어쩔"],											"tags":["케장콘"]},
	{"name":"케장없었습.png",					"keywords":["없었습니다"],														"tags":["케장콘"]},
	{"name":"케장워메.png",						"keywords":["워메"],																	"tags":["케장콘"]},
	{"name":"케장음1.gif",						"keywords":["케장음", "케장음1"],											"tags":["케장콘"]},
	{"name":"케장음2.gif",						"keywords":["케장으음", "케장음2"],										"tags":["케장콘"]},
	{"name":"케장음3.gif",						"keywords":["케장으으음", "케장음3"],									"tags":["케장콘"]},
	{"name":"케장인성.png",						"keywords":["인성다이죠부"],													"tags":["케장콘"]},
	{"name":"케장있었는.png",					"keywords":["있었는데요"],														"tags":["케장콘"]},
	{"name":"케장자기과시.png",				"keywords":["자기과시?", "자기과시"],									"tags":["케장콘"]},
	{"name":"케장저언하.png",					"keywords":["케장저언하", "케장안물4"],								"tags":["케장콘"]},
	{"name":"케장좋은생각.png",				"keywords":["좋은생각"],															"tags":["케장콘"]},
	{"name":"케장지하화.png",					"keywords":["지하화"],																"tags":["케장콘"]},
	{"name":"케장진정헤.png",					"keywords":["진정헤", "진정해"],											"tags":["케장콘"]},
	{"name":"케장축하.png",						"keywords":["케장축하", "축하"],											"tags":["케장콘"]},
	{"name":"케장캡쳐.png",						"keywords":["캡쳐했습니다", "PDF", "캡쳐"],					"tags":["케장콘"]},
	{"name":"케장ㅎ.png",							"keywords":["ㅎㅎㅎㅎㅎㅎ", "ㅎㅎ"],									"tags":["케장콘"]},
	{"name":"케장한심.png",						"keywords":["한심"],																	"tags":["케장콘"]},
	{"name":"케장허미.png",						"keywords":["허미"],																	"tags":["케장콘"]},
	{"name":"케장허어.gif",						"keywords":["케장허어"],															"tags":["케장콘"]},
	{"name":"케장휴지통.png",					"keywords":["휴지통", "케장휴지통"],									"tags":["케장콘"]},
	{"name":"케장흠1.gif",						"keywords":["케장흠", "케장흠1"],											"tags":["케장콘"]},
	{"name":"케장흠2.gif",						"keywords":["케장흐음", "케장흠2"],										"tags":["케장콘"]},
	{"name":"케장흠3.gif",						"keywords":["케장흐으음", "케장흠3"],									"tags":["케장콘"]},

	
	{"name":"눈물소닉너클즈.png",			"keywords":["눈물너클즈"],														"tags":["케장콘", "소닉", "너클즈"]},
	{"name":"눈물소닉.png",						"keywords":["눈물소닉"],															"tags":["케장콘", "소닉"]},
	{"name":"눈물소닉에이미.png",			"keywords":["눈물에이미"],														"tags":["케장콘", "소닉", "에이미"]},
	{"name":"눈물소닉테일즈.png",			"keywords":["눈물테일즈"],														"tags":["케장콘", "소닉", "테일즈"]},

	{"name":"눈물겐지.png",						"keywords":["눈물겐지"],															"tags":["오버워치"]},
	{"name":"눈물디바.png",						"keywords":["눈물디바"],															"tags":["오버워치"]},
	{"name":"눈물라인.png",						"keywords":["눈물라인", "눈물라인하르트"],						"tags":["오버워치"]},
	{"name":"눈물로드.png",						"keywords":["눈물로드", "눈물로드호그"],							"tags":["오버워치"]},
	{"name":"눈물루시우.png",					"keywords":["눈물루시우"],														"tags":["오버워치"]},
	{"name":"눈물리퍼.png",						"keywords":["눈물리퍼"],															"tags":["오버워치"]},
	{"name":"눈물맥크리.png",					"keywords":["눈물맥크리"],														"tags":["오버워치"]},
	{"name":"눈물메르시.png",					"keywords":["눈물메르시"],														"tags":["오버워치"]},
	{"name":"눈물메이.png",						"keywords":["눈물메이"],															"tags":["오버워치"]},
	{"name":"눈물바스.png",						"keywords":["눈물바스", "눈물바스티온"],							"tags":["오버워치"]},
	{"name":"눈물솔져.png",						"keywords":["눈물솔져"],															"tags":["오버워치"]},
	{"name":"눈물시메.png",						"keywords":["눈물시메", "눈물시메트라"],							"tags":["오버워치"]},
	{"name":"눈물위도우.png",					"keywords":["눈물위도우", "눈물위도우메이커"],				"tags":["오버워치"]},
	{"name":"눈물윈스턴.png",					"keywords":["눈물윈스턴"],														"tags":["오버워치"]},
	{"name":"눈물자리야.png",					"keywords":["눈물자리야"],														"tags":["오버워치"]},
	{"name":"눈물정크랫.png",					"keywords":["눈물정크랫"],														"tags":["오버워치"]},
	{"name":"눈물젠야타.png",					"keywords":["눈물젠야타"],														"tags":["오버워치"]},
	{"name":"눈물토르.png",						"keywords":["눈물토르", "눈물토르비욘"],							"tags":["오버워치"]},
	{"name":"눈물트레.png",						"keywords":["눈물트레", "눈물트레이서"],							"tags":["오버워치"]},
	{"name":"눈물파라.png",						"keywords":["눈물파라"],															"tags":["오버워치"]},
	{"name":"눈물한조.png",						"keywords":["눈물한조"],															"tags":["오버워치"]},

	{"name":"우리핵드럼.gif",					"keywords":["우리핵드럼"], 														"tags":["우리핵", "움짤"]},
	{"name":"우리핵박수1.gif",				"keywords":["우리핵박수", "우리핵박수1"], 						"tags":["우리핵", "움짤"]},
	{"name":"우리핵박수2.gif",				"keywords":["우리핵박수2"], 													"tags":["우리핵", "움짤"]},
	{"name":"우리핵박수3.gif",				"keywords":["우리핵박수3"], 													"tags":["우리핵", "움짤"]},
	{"name":"우리핵빵야.gif",					"keywords":["우리핵빵야"], 														"tags":["우리핵", "움짤"]},
	{"name":"우리핵쌍안경.gif",				"keywords":["우리핵쌍안경"], 													"tags":["우리핵", "움짤"]},
	{"name":"우리핵아닌데.gif",				"keywords":["우리핵아닌데"], 													"tags":["우리핵", "움짤"]},
	{"name":"우리핵안녕.gif",					"keywords":["우리핵안녕"],														"tags":["우리핵", "움짤"]},
	{"name":"우리핵투정.gif",					"keywords":["우리핵투정"], 														"tags":["우리핵", "움짤"]},
		
	{"name":"배그로드킬1.png",				"keywords":["로드킬", "로드킬1"],											"tags":["케장콘", "배그"]},
	{"name":"배그로드킬2.png",				"keywords":["로드킬2"], 															"tags":["케장콘", "배그"]},
	{"name":"배그빳다죠.png",					"keywords":["밀베빳다죠"], 														"tags":["배그"]},
	{"name":"배그사이가.png",					"keywords":["사이가"], 																"tags":["배그", "총박이"]},
	{"name":"배그석궁.png",						"keywords":["석궁"], 																	"tags":["케장콘", "배그"]},
	{"name":"배그우지.png",						"keywords":["우지"], 																	"tags":["배그", "총박이"]},
	{"name":"배그은신.png",						"keywords":["은신"], 																	"tags":["배그"]},
	{"name":"배그잘나신분.png",				"keywords":["잘나신분"], 															"tags":["케장콘", "배그"]},
	{"name":"배그한심.gif",						"keywords":["배그한심"], 															"tags":["케장콘", "배그", "움짤"]},
		
	{"name":"레바그안키.png",					"keywords":["그안키", "안키우는데요"],								"tags":["레바"]},
	{"name":"레바띠용.png",						"keywords":["레바띠용"],															"tags":["레바"]},
	{"name":"레바설명.png",						"keywords":["설명들갑"], 															"tags":["레바"]},
	{"name":"레바에라.png",						"keywords":["에라모겠", "에라몰겠"]	,									"tags":["레바"]},
	{"name":"레바와아.png",						"keywords":["레바와아"], 															"tags":["레바"]},
	{"name":"레바이제좀.png",					"keywords":["이제좀볼만"],														"tags":["레바"]},
	{"name":"레바탕탕.gif",						"keywords":["레바탕탕"],															"tags":["레바", "움짤"]},
	{"name":"레바팝콘1.png",					"keywords":["레바팝콘", "레바팝콘1", "팝콘레바2"],		"tags":["레바"]},
	{"name":"레바팝콘2.png",					"keywords":["팝콘레바", "팝콘레바1", "레바팝콘2"],		"tags":["레바"]},
	
	{"name":"참피고마워.png",					"keywords":["고마워미도리"], 													"tags":["참피"]},
	{"name":"참피레후.png",						"keywords":["레후"], 																	"tags":["케장콘", "참피"]},
	{"name":"참피말잇못.png",					"keywords":["말을잇지못하는테치", "말잇못테치"], 			"tags":["케장콘", "참피"]},
	{"name":"참피빳다.png",						"keywords":["당근빳다인테치"], 												"tags":["케장콘", "참피"]},
	{"name":"참피우지챠.png",					"keywords":["우지챠"], 																"tags":["참피"]},
	{"name":"참피죽는데스.png",				"keywords":["죽는데스"], 															"tags":["케장콘", "참피"]},
	{"name":"참피파킨.png",						"keywords":["파킨"], 																	"tags":["참피"]},
	{"name":"참피팝콘.png",						"keywords":["팝콘"], 																	"tags":["참피"]},
	
	{"name":"국뽕김치워리어.png",			"keywords":["김치워리어"], 														"tags":["국뽕"]},
	{"name":"국뽕무궁화1.png",				"keywords":["무궁화1", "무궁화"], 										"tags":["국뽕"]},
	{"name":"국뽕무궁화2.png",				"keywords":["무궁화2"], 															"tags":["국뽕"]},
	{"name":"국뽕세종대왕.png",				"keywords":["세종대왕"], 															"tags":["국뽕"]},
	{"name":"국뽕태극기.png",					"keywords":["태극기"], 																"tags":["국뽕"]},
	{"name":"국뽕펄럭1.gif",					"keywords":["펄럭1", "펄럭"], 												"tags":["국뽕"]},
	{"name":"국뽕펄럭2.gif",					"keywords":["펄럭2"], 																"tags":["국뽕", "움짤"]},
	
	{"name":"카광혼자오셨.gif",				"keywords":["혼자오셨다구요?", "혼자오셨다구요"],			"tags":["카광", "움짤"]},
	{"name":"카광뭐어라고.gif",				"keywords":["뭐어라고?", "뭐어라고"],									"tags":["카광", "움짤"]},
	{"name":"카광저오빠.gif",					"keywords":["저오빠이상해", "아빠저오빠"],						"tags":["카광", "움짤"]},
	{"name":"카광단하나.gif",					"keywords":["단하나"], 																"tags":["카광", "움짤", "트리키타워"]},
	{"name":"카광단두개.gif",					"keywords":["단두개"], 																"tags":["카광", "움짤", "트리키타워"]},
	{"name":"카광단세개.gif",					"keywords":["단세개"], 																"tags":["카광", "움짤", "트리키타워"]},
	
	{"name":"좋은말좋겠다.gif",				"keywords":["좋겠다"], 																"tags":["좋은말콘", "움짤"]},
	{"name":"좋은말네말맞.gif",				"keywords":["네말이맞아", "네말맞"], 									"tags":["좋은말콘", "움짤"]},
	{"name":"좋은말짱이야.gif",				"keywords":["짱이야"], 																"tags":["좋은말콘", "움짤"]},
	{"name":"좋은말멋있다.gif",				"keywords":["정말멋있다"], 														"tags":["좋은말콘", "움짤"]},
	{"name":"좋은말축하해.gif",				"keywords":["축하해"], 																"tags":["좋은말콘", "움짤"]},
	
	{"name":"캐피탈노예일해.png",			"keywords":["노예일해", "일해"],											"tags":["캐피탈리즘호", "루세트"]},
	{"name":"캐피탈퍄산.png",					"keywords":["퍄산", "파산"],													"tags":["캐피탈리즘호", "루세트"]},
	{"name":"캐피탈폴짝.png",					"keywords":["폴짝"],																	"tags":["캐피탈리즘호", "루세트"]},
	{"name":"캐피탈이지붐.jpg",				"keywords":["이지붐"],																"tags":["이지붐", "캐피탈리즘호"]},
	{"name":"캐피탈이지빳다죠.png",		"keywords":["이지빳다죠"],														"tags":["케장콘", "이지붐"]},
	{"name":"캐피탈저딴망겜.png",			"keywords":["저딴망겜"],															"tags":["케장콘", "이지붐"]},

	{"name":"붓싼남이가1.png",				"keywords":["우리가남이가", "우리가남이가1"],					"tags":["붓싼문학"]},
	{"name":"붓싼남이가2.png",				"keywords":["우리가남이가2"], 												"tags":["붓싼문학"]},
	{"name":"붓싼갸아악1.png",				"keywords":["갸아악", "갸아악1"],											"tags":["붓싼문학"]},
	{"name":"붓싼갸아악2.png",				"keywords":["갸아악2"], 															"tags":["붓싼문학"]},
	{"name":"붓싼구와아악.png",				"keywords":["구와아악"], 															"tags":["붓싼문학"]},
	
	{"name":"러브말잇못.gif",					"keywords":["러브말을잇지못하는", "러브말잇못"], 			"tags":["케장콘", "움짤", "핑크"]},
	{"name":"러브빳다죠.gif",					"keywords":["러브빳다죠"], 														"tags":["케장콘", "움짤", "핑크"]},
	{"name":"러브알파카.gif",					"keywords":["러브알파카"], 														"tags":["케장콘", "움짤", "핑크"]},
	{"name":"러브오홍홍.gif",					"keywords":["러브오홍홍"], 														"tags":["케장콘", "움짤", "핑크"]},
	
	{"name":"골든알않.gif",						"keywords":["골든알고싶지않은데스", "골든알않데스"],	"tags":["케장콘", "움짤", "금장"]},
	{"name":"골든빳다죠.gif",					"keywords":["골든당근빳다죠", "골든빳다죠"],					"tags":["케장콘", "움짤", "금장"]},
	{"name":"골든철도죠.gif",					"keywords":["골든철도죠"],														"tags":["케장콘", "움짤", "금장", "철덕"]},
	{"name":"골든도색.gif",						"keywords":["골든도색"],															"tags":["케장콘", "움짤", "금장", "철덕"]},
	{"name":"철도빳다죠.png",					"keywords":["당근철도죠", "철도빳다죠"],							"tags":["케장콘", "철덕"]},
	{"name":"철도역방향.png",					"keywords":["역방향"],																"tags":["케장콘", "철덕"]},
	
	{"name":"문풍당당1.gif",					"keywords":["문풍당당1", "문풍당당"], 								"tags":["문과", "움짤"]},
	{"name":"문풍당당2.gif",					"keywords":["문풍당당2"], 														"tags":["문과", "움짤"]},
	{"name":"문풍당당3.gif",					"keywords":["문풍당당3"], 														"tags":["문과", "움짤"]},
	{"name":"문풍문과지.png",					"keywords":["너문과지"],															"tags":["케장콘", "문과"]},
	
	{"name":"토드흐뭇.png",						"keywords":["토드흐뭇"],															"tags":["베데스다"]},
	{"name":"토드불만.png",						"keywords":["토드불만"],															"tags":["베데스다"]},
	{"name":"토드분노.png",						"keywords":["토드분노"],															"tags":["베데스다"]},
	
	{"name":"핫산발상.png",						"keywords":["핫산발상"], 															"tags":["핫산"]},
	{"name":"핫산쾅.png",							"keywords":["핫산쾅"], 																"tags":["핫산"]},
	{"name":"핫산펑.png",							"keywords":["핫산펑"], 																"tags":["핫산"]},
	
	{"name":"AMD.png",								"keywords":["암드", "AMD", "amd"],										"tags":["컴갤콘"]},
	{"name":"RYZEN.png", 							"keywords":["라이젠", "RYZEN", "ryzen"], 						"tags":["컴갤콘"]},
	
	{"name":"야인시대4딸라.png",			"keywords":["4딸라"],																	"tags":["김두한", "야인시대"]},
	{"name":"야인시대오케이.png",			"keywords":["오케이땡큐"],														"tags":["김두한", "야인시대"]},
	
	{"name":"겐고로아아.png",					"keywords":["아아"],																	"tags":["겐고로"]},
	{"name":"겐고로마치.png",					"keywords":["마치"],																	"tags":["겐고로"]},
	
	{"name":"기타게이븐.png",					"keywords":["게이븐"],																"tags":["스팀", "밸브"]},
	{"name":"기타댕댕.gif",						"keywords":["댕댕콘"],																"tags":["시바", "움짤"]},
	{"name":"기타사이버망령.png",			"keywords":["사이버망령"],														"tags":["케장콘", "록맨", "고인"]},
	{"name":"기타매우정상.png",				"keywords":["매우정상"],															"tags":["원사운드"]},
	{"name":"기타무지개깃발.gif",			"keywords":["무지개깃발"],														"tags":["LGBT", "움짤"]},
];